//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoFactorAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class mortal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mortal()
        {
            this.logs = new HashSet<log>();
        }
    
        public int mortalId { get; set; }
        public string name { get; set; }
        public string nic { get; set; }
        public string filename { get; set; }
        public string template { get; set; }
        public int no_of_minutaes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log> logs { get; set; }
    }
}
