//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TwoFactorAuth
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class log
    {
        public int logId { get; set; }
        public int mortalId { get; set; }
        public Nullable<System.DateTime> dateTime_2 { get; set; }
        public Nullable<int> areaCode { get; set; }
    
        public virtual mortal mortal { get; set; }
    }
}
